// <auto-generated />
using System;
using Finanblue.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Finanblue.Infra.Data.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20230402053557_create")]
    partial class create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("Finanblue.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1L, null, null, null, null, null);

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("company");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activity = "Jogos e derivados",
                            Cnpj = "44788866/0001-9",
                            Name = "Niantic"
                        },
                        new
                        {
                            Id = 2,
                            Activity = "Jogos e derivados",
                            Cnpj = "55877733/0001-9",
                            Name = "Blizzard"
                        });
                });

            modelBuilder.Entity("Finanblue.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1L, null, null, null, null, null);

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseId");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Uma caneta bic preta",
                            Name = "Caneta Preta",
                            Price = 1.5m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Uma caneta bic azul",
                            Name = "Caneta Azul",
                            Price = 1.5m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Uma borracha do Ben10",
                            Name = "Borracha Ben10",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lapiz do Pokemon",
                            Name = "Lapiz Pokemon",
                            Price = 0.55m
                        });
                });

            modelBuilder.Entity("Finanblue.Domain.Entities.ProductsPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1L, null, null, null, null, null);

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("productspurchase");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            PurchaseId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            PurchaseId = 1
                        });
                });

            modelBuilder.Entity("Finanblue.Domain.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1L, null, null, null, null, null);

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.HasKey("Id");

                    b.ToTable("purchase");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Total = 1.1m
                        });
                });

            modelBuilder.Entity("Finanblue.Domain.Entities.Product", b =>
                {
                    b.HasOne("Finanblue.Domain.Entities.Purchase", null)
                        .WithMany("Products")
                        .HasForeignKey("PurchaseId");
                });

            modelBuilder.Entity("Finanblue.Domain.Entities.ProductsPurchase", b =>
                {
                    b.HasOne("Finanblue.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finanblue.Domain.Entities.Purchase", "Purchase")
                        .WithMany("ProductsPurchases")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Finanblue.Domain.Entities.Purchase", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("ProductsPurchases");
                });
#pragma warning restore 612, 618
        }
    }
}
